//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReferance
    {
        public int ReferanceID { get; set; }
        public string ReferanceName { get; set; }
        public string ReferanceStatu { get; set; }
        public string ReferanceImage { get; set; }
    }
}
